apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-auth
  template:
    metadata:
      labels:
        app: go-auth
    spec:
      containers:
        - name: go-auth
          image: shiv1610/go-auth
          env:
            - name: MONGO_URI
              value: "mongodb://go-auth-mongo-srv:27017/go-auth"
            - name: DB_NAME
              value: go-auth
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: go-auth-srv
spec:
  selector:
    app: go-auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
